title   LuminOS Glass Edition (v1.0.0-rc1 Flagship)
linux   /%INSTALL_DIR%/boot/x86_64/vmlinuz-linux-zen
initrd  /%INSTALL_DIR%/boot/x86_64/initramfs-linux-zen.img
options archisobasedir=%INSTALL_DIR% archisosearchuuid=%ARCHISO_UUID% quiet splash loglevel=3 rd.systemd.show_status=false vt.global_cursor_default=0
