[options]
HoldPkg     = pacman glibc
Architecture = x86_64
Color
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Server = https://geo.mirror.pkgbuild.com/core/os/$arch
Server = https://mirror.rackspace.com/archlinux/core/os/$arch
Server = https://mirrors.kernel.org/archlinux/core/os/$arch

[extra]
Server = https://geo.mirror.pkgbuild.com/extra/os/$arch
Server = https://mirror.rackspace.com/archlinux/extra/os/$arch
Server = https://mirrors.kernel.org/archlinux/extra/os/$arch
